apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  namespace: demo
spec:
  type: NodePort
  selector:
    app: hello-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
