apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  namespace: default
  annotations:
    # Tell Image Updater which image to watch
    argocd-image-updater.argoproj.io/image-list: hello-nginx=docker.io/kamalfarah/hello-nginx
    
    # Use newest-build strategy to pick highest number
    argocd-image-updater.argoproj.io/hello-nginx.update-strategy: newest-build
    
    # Only match numeric tags (GitHub run numbers)
    argocd-image-updater.argoproj.io/hello-nginx.allow-tags: regexp:^[0-9]+$
    
    # Write changes back to Git repo
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
      - name: hello-nginx
        image: kamalfarah/hello-nginx:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet: { path: "/", port: 80 }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: "/", port: 80 }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
