apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: hello-nginx=kamalfarah/hello-nginx
    argocd-image-updater.argoproj.io/hello-nginx.update-strategy: latest

 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
      - name: hello-nginx
        image: kamalfarah/hello-nginx:37
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet: { path: "/", port: 80 }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: "/", port: 80 }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
