name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Only trigger when commits are pushed directly to main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout repo
      - name: Checkout source code
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      # Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hello-nginx:${{ github.run_number }}
