name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
 



jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout repo
      - name: Checkout source code
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      # Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hello-nginx:${{ github.run_number }}
     
   #   - name: Replace image placeholder
     #   run: |
        #  sed -i "s|\$DOCKER_IMAGE|${{ secrets.DOCKER_HUB_USERNAME }}/hello-nginx:${{ github.run_number }}|g" k8s/deployment.yaml


      

      # Configure kubeconfig
    #  - name: Set KUBECONFIG
     #   run: |
      #    mkdir -p $HOME/.kube
      #    echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config


      # Deploy to Kubernetes
   #   - name: Inject image tag into manifest
     #   run: |
     #     sed "s|IMAGE_TAG|${{ github.run_number }}|g" k8s/deployment.yaml > k8s/deployment.generated.yaml
     # - name: Deploy to Kubernetes
     #   run: |
          


      #    kubectl apply -f k8s/deployment.generated.yaml

   #       kubectl rollout status deployment hello-nginx -n default
